import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/providers/theme-provider";
import { NextAuthProvider } from "@/providers/next-auth-provider";
import GlobalState from "@/context";
import { Header } from "./components/header";
import { App } from "./App";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-black">
        <NextThemeProvider>
          <NextAuthProvider>
            <GlobalState>
            <App>{children}</App>
            </GlobalState>
          </NextAuthProvider>
        </NextThemeProvider>
      </body>
    </html>
  );
}
